iabbrev <buffer> github GitHub
iabbrev <buffer> jenkins Jenkins
iabbrev <buffer> google Google
iabbrev <buffer> aws AWS
iabbrev <buffer> azure Azure
iabbrev <buffer> cms CMS
iabbrev <buffer> k8s K8s
iabbrev <buffer> linux Linux
iabbrev <buffer> olr OLR
iabbrev <buffer> e2x E2X
iabbrev <buffer> testevovle TestEvolve
iabbrev <buffer> grafana Grafana
iabbrev <buffer> influxdb InfluxDB
