name: Linting and style checking

on: [push, pull_request]

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          # sudo apt-get update
          sudo apt-get install lua-check
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
      - name: Lint
        run: make lint
      - name: Run Tests
        run: make test
